"""Compiling a lexicon into a sampling grammar.

This is the module that makes the constraint real. Everything else in the
project asks the model for things; this one removes the option.

llama.cpp accepts a GBNF grammar and, at every token, masks the logits down to
tokens that could continue a valid string. Give it a grammar whose only
terminals are Blake's words and the model does not "try" to stay inside the
lexicon — no other continuation exists. A word Blake never wrote has
probability zero, structurally, not statistically.

    python -m anima.grammar lexicon/blake.json -o lexicon/blake.gbnf

Design notes, in descending order of how much grief they save:

**Both cases everywhere.** Each word appears lowercase and capitalized, and
either is legal in any position. Enforcing sentence-initial capitals properly
would take a second rule tier, and it would also forbid mid-sentence proper
nouns — London, Thel, Albion — which Blake needs constantly. He capitalised
erratically anyway. Permissiveness costs nothing here.

**Stopping is always legal.** The sentence-count limit is expressed with
optional groups rather than a required count, so the grammar is satisfied
after the first complete sentence and the model may emit EOS. A grammar that
*requires* three sentences produces three sentences, including two the
character had no reason to say.

**Flat alternation, not a prefix trie.** A trie shares prefixes and prunes
faster, and for a very large lexicon it is the right answer. At this size the
flat form is simpler to read and debug, which matters more while the lexicon
is still changing. If sampling turns out slow on real hardware, this is the
first thing to revisit.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Sentence-ending punctuation the character may use. Deliberately no ellipsis:
# it invites trailing off, and a voice that trails off sounds like a failure
# rather than a choice.
TERMINATORS = (".", "?", "!")

# Punctuation permitted after a word inside a sentence.
INTERNAL = (",", ";", ":")


def _escape(literal: str) -> str:
    """Escape a GBNF double-quoted literal."""
    return literal.replace("\\", "\\\\").replace('"', '\\"')


def _word_alternatives(words: set[str]) -> list[str]:
    """Every allowed surface form, lowercase and capitalized, sorted."""
    forms: set[str] = set()
    for word in words:
        if not word:
            continue
        forms.add(word)
        forms.add(word[0].upper() + word[1:])
    return sorted(forms)


def build_gbnf(
    words: set[str],
    *,
    max_sentences: int = 3,
    allow_internal_punctuation: bool = True,
) -> str:
    """Compile a word set into a GBNF grammar.

    Args:
        words: allowed lowercase word forms.
        max_sentences: ceiling on sentences per reply. Each is optional, so
            the model may stop after any one of them.
        allow_internal_punctuation: permit commas, semicolons and colons
            between words. Turning this off yields a flatter, more incantatory
            delivery -- which for some characters is the better sound.
    """
    if not words:
        raise ValueError("Cannot build a grammar from an empty lexicon")
    if max_sentences < 1:
        raise ValueError("max_sentences must be at least 1")

    forms = _word_alternatives(words)
    word_rule = " | ".join(f'"{_escape(form)}"' for form in forms)
    terminator_rule = " | ".join(f'"{_escape(t)}"' for t in TERMINATORS)

    lines = [
        "# Generated by anima.grammar -- do not edit by hand.",
        f"# {len(words):,} lexicon entries -> {len(forms):,} surface forms.",
        "",
        # Each extra sentence is optional, so EOS is legal after any of them.
        "root ::= sentence" + "".join(f' (" " sentence)?' for _ in range(max_sentences - 1)),
        "",
        'sentence ::= word (" " word)* terminator',
        "",
    ]

    if allow_internal_punctuation:
        internal_rule = " | ".join(f'"{_escape(p)}"' for p in INTERNAL)
        lines[lines.index('sentence ::= word (" " word)* terminator')] = (
            'sentence ::= piece (" " piece)* terminator'
        )
        lines += [
            "piece ::= word internal?",
            f"internal ::= {internal_rule}",
            "",
        ]

    lines += [
        f"terminator ::= {terminator_rule}",
        "",
        f"word ::= {word_rule}",
        "",
    ]
    return "\n".join(lines)


def load_words(path: str | Path) -> set[str]:
    """Read the word set out of a compiled lexicon file."""
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    return set(data["words"])


def validate(grammar: str) -> str:
    """Parse the grammar with llama.cpp's own parser. Raises if malformed.

    Worth doing separately from generation: a grammar that llama.cpp rejects
    fails at load time on the target machine, long after you have stopped
    thinking about the generator that produced it.
    """
    try:
        from llama_cpp import LlamaGrammar
    except ImportError as exc:
        raise RuntimeError(
            "llama-cpp-python is not installed, so the grammar cannot be "
            "validated here. pip install llama-cpp-python"
        ) from exc

    LlamaGrammar.from_string(grammar, verbose=False)
    return "parsed by llama.cpp"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="anima.grammar",
        description="Compile a lexicon into a GBNF sampling grammar.",
    )
    parser.add_argument("lexicon", help="compiled lexicon .json from anima.lexicon")
    parser.add_argument("-o", "--output", required=True, help="output .gbnf path")
    parser.add_argument(
        "--max-sentences", type=int, default=3,
        help="ceiling on sentences per reply (default 3)",
    )
    parser.add_argument(
        "--no-internal-punctuation", action="store_true",
        help="forbid commas, semicolons and colons for a flatter delivery",
    )
    parser.add_argument(
        "--no-validate", action="store_true",
        help="skip parsing the result with llama.cpp",
    )
    args = parser.parse_args(argv)

    words = load_words(args.lexicon)
    grammar = build_gbnf(
        words,
        max_sentences=args.max_sentences,
        allow_internal_punctuation=not args.no_internal_punctuation,
    )

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(grammar, encoding="utf-8")

    forms = len(_word_alternatives(words))
    print(f"{len(words):,} lexicon entries -> {forms:,} surface forms")
    print(f"grammar is {len(grammar):,} bytes, {grammar.count(chr(10)):,} lines")
    print(f"Wrote {out}")

    if not args.no_validate:
        try:
            print(f"Validated: {validate(grammar)}")
        except RuntimeError as exc:
            print(f"Not validated: {exc}", file=sys.stderr)
        except Exception as exc:
            print(f"INVALID GRAMMAR: {exc}", file=sys.stderr)
            return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
